services:
  reportproc:
    build: 
      context: .
    volumes:
      - ./src:/report-processor/src
      - ./scrapped_data:/report-processor/scrapped_data
    links: 
      - redis
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile
        - action: sync+restart
          path: src
          target: /report-processor/src
  # scraper:
  #   build: 
  #     context: ../scraper
  #   env_file: ".env"
  #   links: 
  #     - redis
  #   depends_on:
  #     - redis
  redis:
    image: "redis/redis-stack"
    expose:
      - 6379
    # ports:
    #   - 8002:8001
    environment:
      - "REDIS_ARGS=--appendonly yes"
    restart: always
    volumes:
      - "/tmp/job_redis_data:/data"